# Generated by Django 2.2 on 2019-04-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254)),
                ('street', models.TextField(default='201 Presidents Cir')),
                ('city', models.TextField(default='Salt Lake City')),
                ('state', models.TextField(default='Utah')),
                ('zipcode', models.TextField(default='84112')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('inactive', models.BooleanField(default=False)),
            ],
        ),
    ]
