# Generated by Django 2.2 on 2019-04-13 19:46

from django.db import migrations

def create_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User(user_id="1", first_name="Connie", last_name="Consumer", email="connie@email.com", street="1805 Laurelhurst Dr", city="Salt Lake City", state="Utah", zipcode="84108", latitude="40.731166", longitude="-111.817381",).save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
