# Generated by Django 2.2 on 2019-04-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190412_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
