# Generated by Django 2.2 on 2019-04-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190408_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='asset',
            field=models.CharField(max_length=255, null=True, verbose_name='Asset'),
        ),
    ]
