# Generated by Django 2.2 on 2019-04-10 04:16

from django.db import migrations

# def create_data(apps, schema_editor):
#     Device = apps.get_model('devices', 'Device')
#     Device(nickname="Testla", device_type="Tesla Model X").save()


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        # migrations.RunPython(create_data),
    ]
