# Generated by Django 2.2 on 2019-04-12 00:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190412_0047'),
        ('devices', '0002_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AlterField(
            model_name='device',
            name='charge_deadline',
            field=models.TimeField(default=datetime.datetime(2019, 4, 12, 8, 47, 49, 352132), verbose_name='deadline'),
        ),
    ]
