# Generated by Django 2.2 on 2019-04-12 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20190412_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='charge_deadline',
            field=models.TimeField(default=datetime.datetime(2019, 4, 13, 0, 16, 3, 321260), verbose_name='deadline'),
        ),
    ]
