# Generated by Django 2.2 on 2019-04-12 16:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_auto_20190412_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='charge_deadline',
            field=models.TimeField(default=datetime.datetime(2019, 4, 13, 0, 16, 42, 565506), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='device',
            name='owner_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
            preserve_default=False,
        ),
    ]
