# Generated by Django 2.2 on 2019-04-12 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20190412_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='charge_deadline',
            field=models.TimeField(default=datetime.datetime(2019, 4, 13, 4, 25, 28, 728842), verbose_name='deadline'),
        ),
    ]
