# Generated by Django 2.2 on 2019-10-15 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myglobals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyglobalsModel',
            new_name='Myglobals',
        ),
    ]
