# Generated by Django 2.2 on 2019-10-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myglobals', '0002_auto_20191015_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myglobals',
            name='value',
            field=models.DateTimeField(null=True),
        ),
    ]
