# Generated by Django 2.2 on 2019-10-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myglobals', '0004_auto_20191015_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myglobals',
            name='bool_value',
        ),
        migrations.AddField(
            model_name='myglobals',
            name='float_value',
            field=models.FloatField(null=True),
        ),
    ]
