# Generated by Django 2.2 on 2019-10-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myglobals', '0005_auto_20191017_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='myglobals',
            name='bool_value',
            field=models.BooleanField(null=True),
        ),
    ]
