# Generated by Django 2.2 on 2019-04-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255, verbose_name='Nickname')),
                ('asset_type', models.CharField(max_length=255, verbose_name='Type')),
            ],
        ),
    ]
