# Generated by Django 2.2 on 2019-09-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20190911_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='preferences',
        ),
        migrations.AddField(
            model_name='asset',
            name='market_deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='user_deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
