# Generated by Django 2.2 on 2019-04-12 00:47

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190412_0047'),
        ('assets', '0002_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='ownder_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='asset',
            name='percent_of_mrkt_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=3),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(max_length=255, verbose_name='asset_type'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='nickname',
            field=models.CharField(max_length=255, verbose_name='nickname'),
        ),
    ]
