# Generated by Django 2.2 on 2019-09-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20190911_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='market_deadline',
        ),
    ]
