# Generated by Django 2.2 on 2019-04-12 22:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_inactive'),
        ('assets', '0005_auto_20190412_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='percent_of_mrkt_price',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_class',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='capacity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='energy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='flexible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
        migrations.AddField(
            model_name='asset',
            name='power',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='preferences',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='nickname',
            field=models.CharField(max_length=255),
        ),
    ]
