# Generated by Django 2.2 on 2019-04-13 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('energy_sent', models.FloatField(verbose_name='Total kW Sent')),
                ('price_per_kwh', models.DecimalField(decimal_places=2, max_digits=8)),
                ('buyer_asset_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer', to='assets.Asset')),
                ('seller_asset_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller', to='assets.Asset')),
            ],
        ),
    ]
