# Generated by Django 2.2 on 2019-04-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255, verbose_name='nickname')),
                ('device_type', models.CharField(max_length=255, verbose_name='device_type')),
                ('charge_deadline', models.TimeField(auto_now_add=True, verbose_name='deadline')),
            ],
        ),
    ]
