# Generated by Django 2.2 on 2019-09-11 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20190911_1952'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='buyer_asset_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='seller_asset_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='asset_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_with_grid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
